import { Dimensions, Platform, StatusBar, StyleSheet } from 'react-native';

const THEME_COLOR = '#0a7ea4';
const { width } = Dimensions.get('window');
const CARD_SIZE = (width - 48) / 2;
const STATUSBAR_HEIGHT = Platform.OS === 'android' ? StatusBar.currentHeight || 0 : 0;

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#f6fbfd',
    paddingTop: STATUSBAR_HEIGHT,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingTop: 18,
    paddingBottom: 10,
    borderBottomWidth: 0.5,
    borderColor: '#e0f7fa',
    zIndex: 2,
  },
  userBox: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  userName: {
    fontSize: 22,
    fontWeight: 'bold',
    color: THEME_COLOR,
    marginLeft: 8,
    letterSpacing: 0.5,
  },
  logoutBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: THEME_COLOR,
    borderRadius: 24,
    paddingVertical: 8,
    paddingHorizontal: 18,
    gap: 6,
    elevation: 4,
    shadowColor: '#0a7ea4',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 8,
    zIndex: 10,
  },
  logoutText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
    letterSpacing: 0.5,
  },
  grid: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingTop: 18,
    paddingBottom: 32,
    gap: 0,
  },
  card: {
    width: '100%',
    height: 80,
    marginBottom: 16,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.65)',
    borderWidth: 1.5,
    borderColor: '#e0f7fa',
    alignItems: 'center',
    justifyContent: 'flex-start',
    flexDirection: 'row',
    paddingHorizontal: 18,
    paddingVertical: 8,
    shadowColor: '#0a7ea4',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.10,
    shadowRadius: 12,
    elevation: 3,
    overflow: 'hidden',
    gap: 18,
  },
  cardPressed: {
    transform: [{ scale: 0.97 }],
    shadowOpacity: 0.22,
    borderColor: THEME_COLOR,
    backgroundColor: 'rgba(10,126,164,0.08)',
  },
  brandLogo: {
    width: 54,
    height: 54,
    borderRadius: 12,
    marginRight: 18,
    backgroundColor: '#e0f7fa',
    borderWidth: 1,
    borderColor: '#d0f0fa',
    shadowColor: '#0a7ea4',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.10,
    shadowRadius: 8,
    alignSelf: 'center',
  },
  brandName: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#1a2a33',
    textAlign: 'left',
    marginTop: 0,
    letterSpacing: 0.5,
    textShadowColor: '#e0f7fa',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
    alignSelf: 'center',
    minWidth: 100,
  },
}); 